apiVersion: apps/v1
kind: Deployment
metadata:
  name: week3-app
  namespace: devops-week4
spec:
  replicas: 2
  selector:
    matchLabels:
      app: week3-app
  template:
    metadata:
      labels:
        app: week3-app
    spec:
      containers:
      - name: web
        image: sanaqvi573/week3-app:latest
        ports:
        - containerPort: 5000
