apiVersion: v1
kind: Service
metadata:
  name: week3-app-svc
  namespace: devops-week4
spec:
  type: NodePort
  selector:
    app: week3-app
  ports:
    - name: http
      port: 80
      targetPort: 5000
      nodePort: 30081
